services:
  # frontend:
  frontend:
    # command: sh -c "npx prisma db push"
    # command: sh -c "npm run dev"
    # 💡 -p 3000 -H 0.0.0.0 を明示的に追加して、Next.jsの視野を広げる
    command: sh -c "npm run dev -- --port 3000 --hostname 0.0.0.0"
    build:
      context: ./frontend
      # args:
      #  - BUILD_DATE=$(date +%Y%m%d_%H%M%S) # ここでビルド時刻を渡す
      dockerfile: Dockerfile
    # ↓Nginx開通したため（Portsみたいな感じ)
    expose: ["3000"]
    # ports:
    #   - "3000:3000"
    volumes:
       - ./frontend:/app
       - /app/node_modules
       - /app/.next
    environment:
      - WATCHPACK_POLLING=true  # Docker内部でのファイル変更検知（HMR）を確実にする
      - NEXT_TELEMETRY_DISABLED=1
      # 💡 これを追加して、iPhoneのIP（192.168.~）からのHMRアクセスをNext.jsに強制許可する
      - NEXT_PUBLIC_ALLOWED_HOSTS=localhost,127.0.0.1,192.168.0.14
      # depends_on: [backend]
      # ↓環境設定を始めたら
    env_file:
     - ./frontend/.env

    # バックエンド
    # backend:
      # build: 
      #  context: ./backend
      #  # dockerfile: Dockerfile
      # ports: ["8080:8080"]
      # # environment:
      # # # db側の設定（下の方）と完全に一致させる
      # #- SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mylocaldb
      # #- SPRING_DATASOURCE_USERNAME=myuser
      # #- SPRING_DATASOURCE_PASSWORD=mypassword
      # #- SPRING_JPA_HIBERNATE_DDL_AUTO=update
      # volumes:
      #   - ./backend:/app              # Javaのソースも同期
      # depends_on: [db]
      # # command: ./mvnw spring-boot:run 

    # # DB 
    # db:
    #   image: postgres:17-alpine
    #   restart: always
    #   environment:
    #     POSTGRES_USER: myuser
    #     POSTGRES_PASSWORD: mypassword
    #     POSTGRES_DB: mylocaldb
    #   ports:
    #     - "5432:5432"

  nginx:
    image: nginx:alpine
    ports:
       - "80:80"
       - "3000:3000"

      # - "443:443"
    volumes:
       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
       - .:/var/www/hhps:ro
    depends_on:
       - frontend


