services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/target
    ports:
      - "8080:8080"
    environment:
      # db側の設定（下の方）と完全に一致させました！
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mylocaldb
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    command: ./mvnw spring-boot:run # ← depends_on の下あたりに追加

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mylocaldb
    # ports:
    #  - "5432:5432"
    #expose:
    #  - "5432"

  frontend:
    build:
      # Next.jsのソースコードがあるフォルダを指定
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"        # ブラウザから3000番でアクセスできるようにするじぇ
    environment:
      - API_URL=http://backend:8080 # Javaのバックエンドと通信する設定だにょ
    depends_on:
      - backend            # Javaが立ち上がってからNext.jsを動かす設定だじぇ