
import { db } from "@/db";
import { resumesTable } from "@/db/schema/resumes";
export async function insertResumeData() {
    await db.insert(resumesTable).values([
        {
            employmentPeriodSt: "2005/6/1",
            employmentPeriodEd: "2009/10/1",
            projectOverview: "銀行統合プロジェクト",
            assignedPhase: ["コールセンター", "インストラクター"],
            description: "銀行のコールセンター業務で下記を行いました。\n銀行統合統合に伴う、対応依頼(行名・支店名変更等)\n旧ソフト対応(新ソフトインストール・操作説明)\nインストラクター\n銀行統合統合に伴う、対応依頼(行名・支店名変更等)\n旧ソフト対応(新ソフトインストール・操作説明)",
            achievements: "マニュアルを熟読し多数あるソフトや端末ごとの操作で案内に間違いがないように努めました。",
            os: ["Windows"],
            languages: null,
            middlewares: ["EB ソフト"],
            role: "メンバー",
            scale: "50名",
        }, {
            employmentPeriodSt: "2009/11/1",
            employmentPeriodEd: "2011/2/1",
            projectOverview: "リサイクルセンターの窓口対応・業者対応依頼",
            assignedPhase: ["コールセンター", "書類作成", "開発"],
            description: "リサイクルセンターの窓口対応で契約している業者へ対応依頼をする業務です。\n空き時間はスタイルを調整するなども担当しました。\n業務内容は主に下記になります。\nコールセンター\n書類作成\nWeb コーディング（画面作成・修正(リンクを追加したり、静的ページの作成)）",
            achievements: "画面製造がある際は積極的に取り組みCSSの基本を学びました。",
            os: ["Windows"],
            languages: ["HTML", "CSS", "JavaScript", "PHP(Smarty)"],
            middlewares: ["Dreamweaver6", "Eclipse"],
            role: "メンバー",
            scale: "5名",
        }, {
            employmentPeriodSt: "2011/3/1",
            employmentPeriodEd: "2013/7/1",
            projectOverview: "製薬会社の社外・社内問合せ",
            assignedPhase: ["ヘルプデスク(保守)"],
            description: "サイト閲覧者からの問い合わせ対応。\nまた下記も対応。\nデータ抽出作業\nWeb 画面作成\n1. 資材注文画面作成\n2. 社員向け会員獲得キャンペーン画面作成（画面作成・リンク修正・追加・削除等）\n3. 製薬情報変更反映\n4. チーム内運用サイト画面修正（DB参照し問い合わせをチーム内のサイトに表示）",
            achievements: "ヘルプデスクとしてアサインしましたが、画面製造の作業がしたいと問い合わせ対応と同時並行で積極的に画面製造に携わりました。",
            os: ["Windows"],
            languages: ["HTML", "JavaScript", "CSS", "SQL"],
            middlewares: ["Office(Excel・Word)", "SQLServer2008"],
            role: "メンバー",
            scale: "10名",
        }, {
            employmentPeriodSt: "2013/8/1",
            employmentPeriodEd: "2013/9/1",
            projectOverview: "ISMSドキュメント Web化",
            assignedPhase: ["実装"],
            description: "社内システムでISMSのドキュメントをWeb化。\nフロント側:\n 入力制御\nサーバー側:\n 新規登録・編集・確認・削除の機能作成",
            achievements: "作業者がPHPを扱ったことがない担当が多かったので互いにレビューしあいながら進めました。",
            os: ["Windows"],
            languages: ["JavaScript", "PHP", "CSS"],
            middlewares: ["Edit", "TortoiseSVN", "Xampp(環境)"],
            role: "メンバー",
            scale: "5名",
        }, {
            employmentPeriodSt: "2013/10/1",
            employmentPeriodEd: "2014/1/1",
            projectOverview: "お薬手帳電子化に対する問い合わせ対応",
            assignedPhase: ["資料作成"],
            description: "お薬手帳電子化に伴うシステム開発のサポートとしてアサイン。主に開発担当のサポート。",
            achievements: "社内外からの電話窓口への問い合わせ受付。サイト利用方法案内や不具合の聞き取りを作業担当者へ連絡対応をしていました。",
            os: ["Windows"],
            languages: ["SQL"],
            middlewares: ["SQLServer2008", "Oracle SQL Developer", "Office (Excel, PowerPoint)", "Eclipse"],
            role: "メンバー",
            scale: "2名",

        },
        {
            employmentPeriodSt: "2014/2/1",
            employmentPeriodEd: "2015/1/1",
            projectOverview: "ネットアンケートサイトの作成者サポート",
            assignedPhase: ["実装", "資料作成"],
            description: "アンケート作成者のサポートで JScript と JavaScript で下記処理を依頼毎に作成。\nサーバーサイドの処理\n1_動的にアンケートの設問を設置や、回答済みデータにより、アンケートを終了させる処理の設置\n2_アンケート回答者数により、アンケートの入り口の開閉制御\n3_回答数により表示させるページの制御\nフロント側の制御\n1_入力制御\n2_値の即時反映\n(例:月～日の間に缶ビールを何本のんだか？と言うようなアンケートの合計件数を即時に表示、など)\n3_jQuery library の設置\n(例:高速道路の出口調査でマッピングを行う library を設置し、ユーザー何処の出口が危険に感じかるかを、地図からクリックさせ、解答を調査する機能(マッピングの library は既存のもの拡張)\n資料作成",
            achievements: "その日の夕方には配信をするということが多いので、一つの依頼に2時間程度で仕上げるようせねばならず、締め切りに間に合うように努めました。",
            os: ["Windows"],
            languages: ["JavaScript (jQuery)", "JavaScript", "JScript", "HTML", "CSS", "VBA"],
            middlewares: ["Confirmit", "Office (Excel)"],
            role: "メンバー",
            scale: "20名",
        }, {
            employmentPeriodSt: "2015/2/1",
            employmentPeriodEd: "2015/3/1",
            projectOverview: "WEB サーバマイグレーションに伴う WEB IDE 機能変更・追加",
            assignedPhase: ["テスト仕様書作成", "画面設計書作成"],
            description: "WEB サーバマイグレーションに伴う WEB IDE 機能変更・追加で下記を行いました。Web サーバー構築(Windows Server 2008/IIS)テスト仕様書作成、画面設計書作成、実装\n 1_ログイン機能画面 (遷移時に付加されているパラメータと ID/PW を、JSON データの中からマッチングを行い表示するサービスを切り替える)\n 2_WebIDE 上で作成されたファイル・フォルダー階層の Zip 化・DownLoad 機能\n 3_作成した JAVA コードの遠隔コンパイル機能、テスト仕様書作成",
            achievements: "使用言語はPHPですがコンパイル対象はJavaのためファイルが破損しないようになど注意し、コンパイル部分の実装担当と連携しました。",
            os: ["Windows"],
            languages: ["PHP", "JavaScript", "JavaScript (jQuery)", "HTML"],
            middlewares: ["Windows Server 2008/IIS", "NetBeans", "Office"],
            role: "メンバー",
            scale: "10名",
        }, {
            employmentPeriodSt: "2015/3/1",
            employmentPeriodEd: "2015/6/1",
            projectOverview: "保険代理店管理システム",
            assignedPhase: ["・実装", "テスト仕様書作成", "単体テスト"],
            description: "OracleDB 上にある売掛情報を APEX を使いWebブラウザで閲覧可能にする。\nその際に標準で搭載されていない機能や表現を Javascript で実装。\nまた、共通 CSS の正常化を目的としアサインしました。\n業務内容は以下の通りです。\nフロント側:\n 1_APEX のウィザードで作成した入力フィールドに入力制御を Javascript や簡単な PLSQL で制御\n 2_非表示アイテムにセットされた値により、ページの制御\n 3_テキストエリアに貼られた CSV データのトリミング作業 (ラインフィード除去・空白等)\n 4_CSS の整頓\nテスト仕様書作成",
            achievements: "アサイン時に CSS が上書き処理が多く、まずその整頓から入りました。担当していない画面も意識しながら共通スタイルを修正し、全画面に影響がないように注意しました。",
            os: ["Windows"],
            languages: ["HTML", "JavaScript", "JavaScript (jQuery)", "SQL"],
            middlewares: ["Office", "Oracle11g", "OracleAPEX 4.* / 5.0"],
            role: "メンバー",
            scale: "2名",
        }, {
            employmentPeriodSt: "2015/7/1",
            employmentPeriodEd: "2015/8/1",
            projectOverview: "結婚式総合サイト",
            assignedPhase: ["実装", "1_バッチ管理画面 (バッチ実行登録・確認・削除)", "2_プレ環境管理画面 (アップロード画面・レビュー画面・申請画面・承認画面)", "詳細設計書作成", "テスト仕様書作成", "単体テスト"],
            description: "式場から引き出物まで一貫して取り扱うサイトで、主に開発担当としてアサインしました。",
            achievements: "人手不足のための人員強化で短期でアサインされましたが、サーバーサイドの ColdFusion11 はあまりなじみがなく、打ち合わせやレビューを重ね成果物の精度を高めるように努めました。",
            os: ["Windows"],
            languages: ["HTML", "JavaScript", "JavaScript (jQuery)"],
            middlewares: ["Office", "Oracle11g", "Oracle12c", "ColdFusion11"],
            role: "メンバー",
            scale: "30名",
        }, {
            employmentPeriodSt: "2015/9/1",
            employmentPeriodEd: "2016/3/1",
            projectOverview: "売掛買掛管理システム",
            assignedPhase: ["実装", "詳細設計書作成", "テスト仕様書作成", "単体テスト"],
            description: "OracleDB 上にある売掛情報を APEX を使い Web ブラウザで閲覧可能にする。\nその際に標準で搭載されていない機能や表現を JavaScript で実装。\n業務内容は以下の通りです。、ORACLE APEX を利用した売掛買掛管理システム画面作成\nフロント側:\n 1_入力制御 (Js・PLSQL)\n 2_Hidden 値により入力欄の表示非表示切り替え\n 3_指定した ID にスクロールバーを付加する共通機能作成\n 4_データ編集中のページ遷移にダイアログをポップアップする共通機能作成\n\nサーバー側:\n 1_パッケージを作成し画面内の登録・修正・削除 処理作成\n 2_日付制御機能作成(グローバル言語対応)",
            achievements: "jQuery で作りこむのではなくなるべく標準機能を使うように意識しました。",
            os: ["Windows"],
            languages: ["SQL", "SQL (PL/SQL)", "HTML", "JavaScript", "JavaScript (jQuery)"],
            middlewares: ["Office", "Oracle11g", "APEX 4.2", "Oracle SQL Developer"],
            role: "メンバー",
            scale: "15名",
        }, {
            employmentPeriodSt: "2016/3/1",
            employmentPeriodEd: "2016/9/1",
            projectOverview: "携帯電話会社のキャンペーンページ作成",
            assignedPhase: ["・実装"],
            description: "携帯電話会社のキャンペーンページの作成で、デザイン画像から画面作成。",
            achievements: "デザイナーの指示どおり 1px のずれがないように画面を作成。また共通テンプレートを使用し独自コードにならないように徹底しました。",
            os: ["Windows"],
            languages: ["HTML", "JavaScript", "JavaScript (jQuery)"],
            middlewares: [],
            role: "メンバー",
            scale: "40名",
        }, {
            employmentPeriodSt: "2016/9/1",
            employmentPeriodEd: "2017/3/1",
            projectOverview: "売掛買掛管理システム",
            assignedPhase: ["実装", "単体テスト"],
            description: "OracleDB 上にある売掛情報を APEX を使い Web ブラウザで閲覧可能にする。\nその際に標準で搭載されていない機能や表現を JavaScript で実装。\n業務内容は以下の通りです。実装\nフロント側:\n 1_入力制御 (Js・PLSQL)\n 2_Hidden 値により入力欄の表示非表示切り替え\n 3_指定した ID にスクロールバーを付加する共通機能作成\n 4_データ編集中のページ遷移にダイアログをポップアップする共通機能作成\nサーバー側:\n 1_パッケージを作成し画面内の登録・修正・削除 処理作成、詳細設計書作成、テスト仕様書作成、単体テスト",
            achievements: "jQuery で作りこむのではなくなるべく標準機能を使うように意識しました。後任に引き継ぎやすいコーディングにするために。",
            os: ["Windows"],
            languages: ["SQL", "SQL (PL/SQL)", "HTML", "JavaScript", "JavaScript (jQuery)"],
            middlewares: ["Office", "Oracle12c", "APEX 4.2", "Oracle SQL Developer"],
            role: "メンバー",
            scale: "15名",
        }, {
            employmentPeriodSt: "2017/3/1",
            employmentPeriodEd: "2022/3/1",
            projectOverview: "店舗来店予約システム開発\nコールセンター受電システム開発",
            assignedPhase: ["詳細設計", "実装", "単体テスト"],
            description: "タブレットの店舗来店予約システムと、其後はコールセンターの受電システムの機能追加・改修、チャット過去履歴表示画面、SMS 送信画面作成などを行いました。\n業務内容は下記の通りです。要望から詳細設計作成・実装・単体テスト",
            achievements: "他チームとも製造画面が重複してしまうことも多々あったので、各チームと連携を取りながら開発を進めました。ソースコードが上書きになるとバグにつながるから。",
            os: ["Windows", "macOS"],
            languages: ["JavaScript", "JavaScript (jQuery)", "HTML", "CSS", "JavaScript (Backbone.js)", "JavaScript (Marionette.js)", "SQL"],
            middlewares: ["VSCODE", "GitHub Desktop", "Oracle", "Dbeaver"],
            role: "メンバー",
            scale: "50名",
        }, {
            employmentPeriodSt: "2022/3/1",
            employmentPeriodEd: "2026/3/1",
            projectOverview: "母体・胎児情報を活用した集中監視システム開発",
            assignedPhase: ["実装", "単体テスト (Vitest を用いた自動テスト作成)"],
            description: "母体管理をサポートする分娩監視装置で、各医療機器からのあらゆる情報を Web アプリに表示。主に設定画面の開発を担当し業務内容は下記になります。Vue.js を活用した画面作成、WebSocket (mqtt) から受信したデータのリアルタイム反映\nリーダー機能 (WebSerial/WebUsb を用いて情報を読み取り画面反映)、タブレット・スマートフォン用にレスポンシブ対応",
            achievements: "ほかメンバーが見やすいように保守性の高いコーディングを心掛けました。そのためにレビューを積極的に行ってもらい保守性の向上を図った。",
            os: ["Windows"],
            languages: ["JavaScript", "HTML", "CSS", "JavaScript(Vue.js (Ver.2 / Ver.3))"],
            middlewares: ["VS CODE", "GitHub Desktop", "Stoplight", "Mongodb"],
            role: "メンバー",
            scale: "10人",
        }
    ]);
}
// スクリプトの最下部に呼び出しがあるか確認
insertResumeData()
    .then(() => {
        process.exit(0);
    })
    .catch((err) => {
        console.error("Seeding failed:", err);
        process.exit(1);
    });